logging:
  level:
    root: info
server:
  port: 8081

config:
  topic : "projects/krungthai-goveco-dev/topics/topic.register.gove.success"
  subscriptions: "projects/krungthai-goveco-dev/subscriptions/sub.register.gove.success.backup"

spring:
  cloud:
    gcp:
      pubsub:
        project-id: krungthai-goveco-dev
        credentials:
          location: file:${PWD}/src/main/resources/goveco-hh3spn-pubsub.json
