logging:
  level:
    root: info
spring:
  webservices:
    path: /demo
server:
  port: 8080

gcp:
  project-2:
    topic: sample.topic
    subscription: sample.response.subscription
    project-id: sample-project-one
    credentialpath: /xxx/service-account.json
  project-1:
    topic: sample.topic
    subscription: sample.response.subscription
    project-id: sample-project-two
    credentialpath: /xxx/service-account.json